apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemeral-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeral-hello-world
  template:
    metadata:
      labels:
        app: ephemeral-hello-world
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "1000m"